name: rezult_test
description: A flutter technical task

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  tuple: ^2.0.2
  get_it: ^7.6.4
  cached_network_image: ^3.3.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: TestLocalization
  main_locale: pl